const actions = {
	SET_STATE: "actions.SET_STATE",
	GET_MAIN_DASHBOARD_DATA: "actions.GET_MAIN_DASHBOARD_DATA",
	GET_TOTALS_COUNTRIES: "actions.GET_TOTALS_COUNTRIES",
	GET_TIME_LINE_COUNTRY: "actions.GET_TIME_LINE_COUNTRY",
	GET_DASHBOARD_COUNTRY: "actions.GET_DASHBOARD_COUNTRY"
};

export default actions;
